apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-ns.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.0/manifests/install.yaml
- in-cluster.yaml
- system-project.yaml

patches:
- path: argocd-cm.yaml

namespace: argocd